---
config:
  start_point:
    x: 595
    y: 913

  bank:
    x: 612
    y: 886

  points:
    - [595, 913]
    - [714, 939]
    - [667, 873]

  discord:
    post_statistics: true
    webhook_url: https://discord.com/api/webhooks/860503436158959676/2qflDmu2HJ4BzFDd_wWztN4XripnSBMPcI_pqKNyq1PApPhUYb_9y09CURCpd1TFHT96
