---
config:
  start_point:
    x: 519
    y: 873

  bank:
    x: 612
    y: 886

  points:
    - [519, 873]
    - [488, 896]
    - [449, 879]

  discord:
    post_statistics: true
    webhook_url: https://discord.com/api/webhooks/860503436158959676/2qflDmu2HJ4BzFDd_wWztN4XripnSBMPcI_pqKNyq1PApPhUYb_9y09CURCpd1TFHT96
